platform :ios,'8.0'

use_frameworks!
inhibit_all_warnings!

target :FYDD do
    
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'JPush'
pod 'YYKit'
pod 'Masonry'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'Bugly'
pod 'IQKeyboardManager'
pod 'LCActionSheet'
pod 'SDCycleScrollView','~> 1.75'
pod 'CWLateralSlide', '~> 1.6.5'
pod 'ZLPhotoBrowser'
pod 'FSCalendar'
pod 'WechatOpenSDK'
pod 'ZXingObjC', '~> 3.6.4'
pod 'BMPlayer'
pod 'UMCCommon'
#pod 'UMCSecurityPlugins'
pod 'UMCAnalytics'
pod 'UMCPush'
pod 'UMCShare/UI'
#pod 'UMCShare'
pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/Sina'
pod 'AlipaySDK-iOS'
pod 'RNCachingURLProtocol'
#无限轮播
pod 'SDCycleScrollView','>= 1.80'

pod 'ZFPlayer'
pod 'FDFullscreenPopGesture'
end
